name: bolter_flutter
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  animations: ^1.1.2
  provider: ^4.3.2
  platform_info: ^1.1.1+3
  sembast: ^2.4.7+6
  hive_flutter: ^0.3.1
  bolter:
    git:
      url: https://github.com/Renesanse/bolter.git

dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.1
  pedantic: ^1.9.0
  test: ^1.15.3
