name: bolter_flutter
version: 1.0.4
description: based on bolter library extensions for manage widgets and state
homepage: https://github.com/Renesanse/bolter_flutter

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2
  animations: ^1.1.2
  provider: ^4.3.2+2
  platform_info: ^2.0.1
  hive_flutter: ^0.3.1
  hive: ^1.4.4
  bolter: ^1.0.1

dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.1
  pedantic: ^1.9.0
  test: ^1.15.3
