name: bolter_flutter
version: 5.1.6
description: based on bolter library extensions for manage widgets and state
homepage: https://github.com/Renesanse/bolter_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  after_layout: ^1.1.0
  animations: ^2.0.0
  bolter: ^2.0.1
  flutter:
    sdk: flutter
  hive: 2.0.0
  hive_flutter: ^1.0.0
  provider: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.5
  hive_generator: 1.0.1
  lint: ^1.5.3
  test: ^1.17.9
